# Generated by Django 4.1.7 on 2023-03-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                            ("approved", "Approved"),
                            ("cancelled", "Cancelled"),
                            ("terminated", "Terminated"),
                            ("completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("num_guests", models.IntegerField()),
                ("num_beds", models.IntegerField()),
                ("num_baths", models.IntegerField()),
                ("images", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("amenities", models.CharField(max_length=200)),
                ("available_dates", models.DateTimeField(null=True)),
            ],
        ),
    ]
