# Generated by Django 4.1.7 on 2023-03-20 00:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_property_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="owner",
            new_name="user",
        ),
    ]
