# Generated by Django 4.2 on 2023-04-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_owner_property_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
    ]
